"""Render the public ``outrage`` ArgumentParser as Markdown.

The parser is the source of truth for command names, usage, descriptions and
argument help. This deliberately uses argparse's formatter for each argument
invocation instead of reproducing its rules for choices, metavariables and
aliases here.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

from outrage.cli import argument_parser


def _paragraph(text: str) -> str:
    """Collapse argparse prose and wrap it as one Markdown paragraph."""
    return textwrap.fill(" ".join(text.split()), width=100, break_on_hyphens=False)


def _one_line(text: str) -> str:
    """Collapse argparse prose for a list item."""
    return " ".join(text.split())


def _usage(parser: argparse.ArgumentParser) -> str:
    """Return argparse's usage without its label and matching indentation."""
    lines = parser.format_usage().strip().splitlines()
    prefix = "usage: "
    if lines and lines[0].startswith(prefix):
        lines[0] = lines[0][len(prefix) :]
        indentation = " " * len(prefix)
        lines[1:] = [
            line[len(indentation) :] if line.startswith(indentation) else line for line in lines[1:]
        ]
    return "\n".join(lines)


def _subcommands(
    parser: argparse.ArgumentParser,
) -> list[tuple[str, argparse.ArgumentParser, str]]:
    """Return the parser's subcommands in their declared order."""
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            help_by_name = {choice.dest: choice.help for choice in action._choices_actions}
            return [
                (name, command, help_by_name.get(name, ""))
                for name, command in action.choices.items()
            ]
    return []


def _arguments(parser: argparse.ArgumentParser) -> list[tuple[str, str]]:
    """Return the visible argument invocations and their help text."""
    formatter = parser._get_formatter()
    arguments = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction) or action.help == argparse.SUPPRESS:
            continue
        invocation = formatter._format_action_invocation(action)
        arguments.append((invocation, action.help or ""))
    return arguments


def _append_arguments(lines: list[str], parser: argparse.ArgumentParser) -> None:
    """Append the visible arguments of ``parser`` to ``lines``."""
    arguments = _arguments(parser)
    if arguments:
        lines.extend(["", "### Arguments", ""])
        for invocation, help_text in arguments:
            lines.append(f"- `{invocation}` - {_one_line(help_text)}")


def render(parser: argparse.ArgumentParser) -> str:
    """Render ``parser`` and each of its immediate subcommands as Markdown."""
    commands = _subcommands(parser)
    lines = [
        "<!-- Generated by tools/render_cli.py; do not edit by hand. -->",
        "",
        "# The Outrage command line",
        "",
        _paragraph(parser.description or ""),
        "",
        "## Usage",
        "",
        "```text",
        _usage(parser),
        "```",
    ]
    _append_arguments(lines, parser)

    if commands:
        lines.extend(["", "## Commands", ""])
        for name, _, summary in commands:
            lines.append(f"- [`{name}`](#{name}) - {_one_line(summary)}")

    for name, command, _ in commands:
        lines.extend(
            [
                "",
                f"## `{name}`",
                "",
                _paragraph(command.description or ""),
                "",
                "### Usage",
                "",
                "```text",
                _usage(command),
                "```",
            ]
        )
        _append_arguments(lines, command)

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("output", type=Path, help="Markdown file to write")
    args = parser.parse_args(argv)

    try:
        args.output.write_text(render(argument_parser()), encoding="utf-8")
    except OSError as error:
        print(error, file=sys.stderr)
        return 1
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
